"""Equipment class affinity (from Improved-Logic fork item_table)."""
from __future__ import annotations
from typing import Dict, FrozenSet, Optional

ITEM_CLASS_AFFINITY: Dict[str, str] = {
    "Amberite Boomstick": "B",
    "Amberite Halberd": "F",
    "Amberite Shield": "FM",
    "Amberite Sword": "F",
    "Amberite Warstar": "F",
    "Aquapetal Staff": "M",
    "Berserker Chestpiece": "F",
    "Berserker Leggings": "F",
    "Coldgeist Blade": "F",
    "Coldgeist Bow": "B",
    "Coldgeist Frostcaller": "M",
    "Coldgeist Punisher": "F",
    "Colossus Tone": "M",
    "Cryo Cane": "M",
    "Cryotribe Spear": "F",
    "Crypt Blade": "F",
    "Crypt Bow": "B",
    "Crypt Buckler": "FM",
    "Crypt Pounder": "F",
    "Cryptcall Bell": "M",
    "Cryptsinge Halberd": "F",
    "Cryptsinge Katars": "B",
    "Daemon Shield": "FM",
    "Dawn Mace": "F",
    "Deadwood Axe": "F",
    "Deathgel Shivs": "B",
    "Deathknight Runeblade": "F",
    "Demicrypt Bauble": "M",
    "Demicrypt Blade": "F",
    "Demicrypt Bow": "B",
    "Demicrypt Buckler": "FM",
    "Dense Hammer": "F",
    "Dense Katars": "B",
    "Dense Mace": "F",
    "Dense Shield": "FM",
    "Dense Spear": "F",
    "Dolkin's Axe": "F",
    "Executioner Leggings": "F",
    "Executioner Vestment": "F",
    "Femur Club": "F",
    "Fender Garb": "B",
    "Fender Leggings": "B",
    "Fier Blade": "F",
    "Firebreath Blade": "F",
    "Flamepetal Staff": "M",
    "Flametribe Spear": "F",
    "Focus Circlet": "M",
    "Focusi Glasses": "M",
    "Follycannon": "B",
    "Frostbite Claws": "B",
    "Fuguefall Duster": "B",
    "Fuguefall Pants": "B",
    "Geist Scythe": "F",
    "Geistlord Claws": "B",
    "Gilded Sword": "F",
    "Golemfist Katars": "B",
    "Hellsludge Shivs": "B",
    "Iris Shield": "FM",
    "Irisun Shield": "FM",
    "Iron Axehammer": "F",
    "Iron Bell": "M",
    "Iron Bow": "B",
    "Iron Katars": "B",
    "Iron Scepter": "M",
    "Iron Shield": "FM",
    "Iron Spear": "F",
    "Iron Sword": "F",
    "Ironbark Sword": "F",
    "King Breastplate": "F",
    "King Greaves": "F",
    "Lord Breastplate": "F",
    "Lord Greaves": "F",
    "Magilord Boots": "M",
    "Magilord Overalls": "M",
    "Magitek Burstgun": "B",
    "Marrow Bauble": "M",
    "Mekspear": "F",
    "Mekspike Bow": "B",
    "Menace Bow": "B",
    "Mini Geist Scythe": "F",
    "Mithril Bell": "M",
    "Mithril Bow": "B",
    "Mithril Greatsword": "F",
    "Mithril Halberd": "F",
    "Mithril Katars": "B",
    "Mithril Scepter": "M",
    "Mithril Shield": "FM",
    "Mithril Sword": "F",
    "Necroroyal Bow": "B",
    "Necroroyal Halberd": "F",
    "Nethercrypt Bauble": "M",
    "Nethercrypt Blade": "F",
    "Nethercrypt Shield": "FM",
    "Nulrok Mace": "F",
    "Nulrok Spear": "F",
    "Omen Shield": "FM",
    "Petrified Bow": "B",
    "Poltergeist Scythe": "F",
    "Pyre Cane": "M",
    "Quake Pummeler": "F",
    "Ragespear": "F",
    "Reaper Gi": "B",
    "Reaper Leggings": "B",
    "Reapsow Garb": "B",
    "Reapsow Pants": "B",
    "Rigor Buckler": "FM",
    "Rude Blade": "F",
    "Rummok Bladerings": "B",
    "Runic Katars": "B",
    "Rustweary Shield": "FM",
    "Rustwise Shield": "FM",
    "Ryzer Greataxe": "F",
    "Sapphite Bell": "M",
    "Sapphite Katars": "B",
    "Sapphite Mindhat": "M",
    "Sapphite Scepter": "M",
    "Sapphite Shield": "FM",
    "Sapphite Spear": "F",
    "Serrated Blade": "F",
    "Serrated Knuckles": "B",
    "Serrated Longbow": "B",
    "Serrated Spear": "F",
    "Sinner Bardiche": "F",
    "Slabton Shield": "FM",
    "Slime Diva Baton": "M",
    "Slimecrust Blade": "F",
    "Slimecrust Katars": "B",
    "Slimek Axehammer": "F",
    "Slimek Shield": "FM",
    "Slimek Shivs": "B",
    "Splitbark Club": "F",
    "Splitbark Scepter": "M",
    "Stone Greatblade": "F",
    "Torrentius Longbow": "B",
    "Valdur Blade": "F",
    "Vile Blade": "F",
    "Voalstark Wand": "M",
    "Witchlock Loincloth": "M",
    "Witchlock Robe": "M",
    "Witchwizard Garterbelt": "M",
    "Witchwizard Robe": "M",
    "Wizlad Hood": "M",
    "Wizlad Robe": "M",
    "Wizwand": "M",
    "Wooden Shield": "FM",
}

CLASS_FILTER_MAP: Dict[int, Optional[FrozenSet[str]]] = {
    0: None,
    1: frozenset({"F"}),
    2: frozenset({"M"}),
    3: frozenset({"B"}),
    4: frozenset({"F", "M"}),
    5: frozenset({"F", "B"}),
    6: frozenset({"M", "B"}),
}


def item_passes_class_filter(filter_value: int, item_name: str) -> bool:
    """Universal items (no affinity) always pass."""
    selected = CLASS_FILTER_MAP.get(filter_value)
    if selected is None:
        return True
    affinity = ITEM_CLASS_AFFINITY.get(item_name)
    if affinity is None:
        return True
    return bool(set(affinity) & selected)

