# File is Auto-generated, see: [https://github.com/SWCreeperKing/ApWorldFactories/tree/master/ApWorldFactories/Games]

quests = [
    ["A Warm Welcome", "Sanctum"],
    ["Communing Catacombs", "Sanctum"],
    ["Diva Must Die", "Sanctum"],
    ["The Keep Within", "Sanctum"],
    ["Tethering Grove", "Sanctum"],
    ["The Glyphik Booklet", "Sanctum"],
    ["Cleaning Terrace", "Sanctum"],
    ["Ancient Beings", "Sanctum"],
    ["Wicked Wizboars", "Sanctum"],
    ["Spiraling In The Grove", "Sanctum"],
    ["Hell In The Grove", "Sanctum"],
    ["Nulversa", "Sanctum"],
    ["Finding Ammagon", "Sanctum"],
    ["The Colossus", "Sanctum"],
    ["Night Spirits", "Sanctum"],
    ["Ridding Slimes", "Sanctum"],
    ["Huntin' Hogs", "Sanctum"],
    ["Purging the Grove", "Sanctum"],
    ["Cleansing the Grove", "Sanctum"],
    ["Call of Fury", "Sanctum"],
    ["Mastery of Strength", "Sanctum"],
    ["Beckoning Foes", "Sanctum"],
    ["Ghostly Goods", "Sanctum"],
    ["Makin' a Mekspear", "Sanctum"],
    ["Makin' a Wizwand", "Sanctum"],
    ["Makin' a Vile Blade", "Sanctum"],
    ["Makin' a Golem Chestpiece", "Sanctum"],
    ["Makin' a Ragespear", "Sanctum"],
    ["Makin' a Monolith Chestpiece", "Sanctum"],
    ["Makin' a Firebreath Blade", "Sanctum"],
    ["Makin' a Follycannon", "Sanctum"],
    ["Summore' Spectral Powder!", "Sanctum"],
    ["Makin' More Mekspears", "Sanctum"],
    ["Makin' More Wizwands", "Sanctum"],
    ["Makin' More Vile Blades", "Sanctum"],
    ["Summore' Golem Chestpieces", "Sanctum"],
    ["Makin' More Ragespears", "Sanctum"],
    ["Summore' Monolith Chestpieces", "Sanctum"],
    ["Summore' Firebreath Blades", "Sanctum"],
    ["Makin' More Follycannons", "Sanctum"],
    ["Focusin' in", "Sanctum"],
    ["Mastery of Dexterity", "Sanctum"],
    ["Whatta' Rush!", "Sanctum"],
    ["The Voice of Zuulneruda", "Arcwood Pass"],
    ["Killing Tomb", "Arcwood Pass"],
    ["Purging the Undead", "Arcwood Pass"],
    ["Rattlecage Rage", "Arcwood Pass"],
    ["Consumed Madness", "Arcwood Pass"],
    ["Eradicating the Undead", "Arcwood Pass"],
    ["Reviling the Rageboars", "Bularr Fortress"],
    ["Gatling Galius", "Bularr Fortress"],
    ["Reviling more Rageboars", "Bularr Fortress"],
    ["Facing Foes", "Bularr Fortress"],
    ["The Gall of Galius", "Bularr Fortress"],
    ["Dense Ingots", "Sanctum"],
    ["Amberite Ingots", "Sanctum"],
    ["Sapphite Ingots", "Sanctum"]
]

levels = [
    ["Reach Level 2", "Menu"],
    ["Reach Level 4", "Menu"],
    ["Reach Level 6", "Menu"],
    ["Reach Level 8", "Menu"],
    ["Reach Level 10", "Menu"],
    ["Reach Level 12", "Menu"],
    ["Reach Level 14", "Menu"],
    ["Reach Level 16", "Menu"],
    ["Reach Level 18", "Menu"],
    ["Reach Level 20", "Menu"],
    ["Reach Level 22", "Menu"],
    ["Reach Level 24", "Menu"],
    ["Reach Level 26", "Menu"],
    ["Reach Level 28", "Menu"],
    ["Reach Level 30", "Menu"],
    ["Reach Level 32", "Menu"]
]

merchants = [
    ["Buy Item #1 from Sally's Nook", "Sanctum"],
    ["Buy Item #2 from Sally's Nook", "Sanctum"],
    ["Buy Item #3 from Sally's Nook", "Sanctum"],
    ["Buy Item #4 from Sally's Nook", "Sanctum"],
    ["Buy Item #5 from Sally's Nook", "Sanctum"],
    ["Buy Item #1 from Skrit's Sikrit Market", "Sanctum"],
    ["Buy Item #2 from Skrit's Sikrit Market", "Sanctum"],
    ["Buy Item #3 from Skrit's Sikrit Market", "Sanctum"],
    ["Buy Item #4 from Skrit's Sikrit Market", "Sanctum"],
    ["Buy Item #5 from Skrit's Sikrit Market", "Sanctum"],
    ["Buy Item #1 from Frankie's Goods", "Arcwood Pass"],
    ["Buy Item #2 from Frankie's Goods", "Arcwood Pass"],
    ["Buy Item #3 from Frankie's Goods", "Arcwood Pass"],
    ["Buy Item #4 from Frankie's Goods", "Arcwood Pass"],
    ["Buy Item #5 from Frankie's Goods", "Arcwood Pass"],
    ["Buy Item #1 from Dye Merchant", "Sanctum"],
    ["Buy Item #2 from Dye Merchant", "Sanctum"],
    ["Buy Item #3 from Dye Merchant", "Sanctum"],
    ["Buy Item #4 from Dye Merchant", "Sanctum"],
    ["Buy Item #5 from Dye Merchant", "Sanctum"],
    ["Buy Item #1 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
    ["Buy Item #2 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
    ["Buy Item #3 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
    ["Buy Item #4 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
    ["Buy Item #5 from Tesh's Wares", "Sanctum Catacombs lvl 2"],
    ["Buy Item #1 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
    ["Buy Item #2 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
    ["Buy Item #3 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
    ["Buy Item #4 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
    ["Buy Item #5 from Nesh's Wares", "Sanctum Catacombs lvl 3"],
    ["Buy Item #1 from Rikko's Treasures", "Crescent Grove lvl 1"],
    ["Buy Item #2 from Rikko's Treasures", "Crescent Grove lvl 1"],
    ["Buy Item #3 from Rikko's Treasures", "Crescent Grove lvl 1"],
    ["Buy Item #4 from Rikko's Treasures", "Crescent Grove lvl 1"],
    ["Buy Item #5 from Rikko's Treasures", "Crescent Grove lvl 1"],
    ["Buy Item #1 from Cotoo's Treasures", "Crescent Grove lvl 2"],
    ["Buy Item #2 from Cotoo's Treasures", "Crescent Grove lvl 2"],
    ["Buy Item #3 from Cotoo's Treasures", "Crescent Grove lvl 2"],
    ["Buy Item #4 from Cotoo's Treasures", "Crescent Grove lvl 2"],
    ["Buy Item #5 from Cotoo's Treasures", "Crescent Grove lvl 2"],
    ["Buy Item #1 from Ruka's Furnace", "Sanctum"],
    ["Buy Item #2 from Ruka's Furnace", "Sanctum"],
    ["Buy Item #3 from Ruka's Furnace", "Sanctum"],
    ["Buy Item #4 from Ruka's Furnace", "Sanctum"],
    ["Buy Item #5 from Ruka's Furnace", "Sanctum"],
    ["Buy Item #1 from Torta's Fishing Shack", "Sanctum"],
    ["Buy Item #2 from Torta's Fishing Shack", "Sanctum"],
    ["Buy Item #3 from Torta's Fishing Shack", "Sanctum"],
    ["Buy Item #4 from Torta's Fishing Shack", "Sanctum"],
    ["Buy Item #5 from Torta's Fishing Shack", "Sanctum"],
    ["Buy Item #1 from Mad Statue's Gift", "Sanctum"],
    ["Buy Item #2 from Mad Statue's Gift", "Sanctum"],
    ["Buy Item #3 from Mad Statue's Gift", "Sanctum"],
    ["Buy Item #4 from Mad Statue's Gift", "Sanctum"],
    ["Buy Item #5 from Mad Statue's Gift", "Sanctum"]
]

professions = [
    ["Fishing Lv. 1", "Menu"],
    ["Fishing Lv. 2", "Menu"],
    ["Fishing Lv. 3", "Menu"],
    ["Fishing Lv. 4", "Menu"],
    ["Fishing Lv. 5", "Menu"],
    ["Fishing Lv. 6", "Menu"],
    ["Fishing Lv. 7", "Menu"],
    ["Fishing Lv. 8", "Menu"],
    ["Fishing Lv. 9", "Menu"],
    ["Fishing Lv. 10", "Menu"],
    ["Mining Lv. 1", "Menu"],
    ["Mining Lv. 2", "Menu"],
    ["Mining Lv. 3", "Menu"],
    ["Mining Lv. 4", "Menu"],
    ["Mining Lv. 5", "Menu"],
    ["Mining Lv. 6", "Menu"],
    ["Mining Lv. 7", "Menu"],
    ["Mining Lv. 8", "Menu"],
    ["Mining Lv. 9", "Menu"],
    ["Mining Lv. 10", "Menu"]
]

achievements = [
    ["A New Journey", "Sanctum"],
    ["Clearing Catacombs (1-6)", "Sanctum Catacombs lvl 1"],
    ["Clearing Catacombs (6-12)", "Sanctum Catacombs lvl 2"],
    ["Clearing Catacombs (12-18)", "Sanctum Catacombs lvl 3"],
    ["Clearing Grove (15-20)", "Crescent Grove lvl 1"],
    ["Clearing Grove (20-25)", "Crescent Grove lvl 2"],
    ["Altered Vision", "Sanctum"],
    ["Scaling the Tower", "Sanctum"],
    ["Rude!", "Sanctum"],
    ["Fashion Sense", "Sanctum"],
    ["Trout Master", "Sanctum"],
    ["Skill Student", "Sanctum"]
]

bosses = [
    ["Slime Diva", "Effold Terrace"],
    ["Lord Zuulneruda", "Sanctum Catacombs lvl 2"],
    ["Lord Kaluuz", "Sanctum Catacombs lvl 3"],
    ["Colossus", "Crescent Grove lvl 1"],
    ["Valdur", "Crescent Grove lvl 2"],
    ["Galius", "Bularr Fortress"]
]

from .ProfessionToolData import PROFESSION_TOOL_BUYS

profession_tool_buys = [[location_name, "Menu"] for location_name, _ in PROFESSION_TOOL_BUYS]

location_dict = [
    *[items[0] for items in quests],
    *[items[0] for items in levels],
    *[items[0] for items in merchants],
    *[items[0] for items in professions],
    *[items[0] for items in achievements],
    *[items[0] for items in bosses],
    *[items[0] for items in profession_tool_buys],
]

location_grind_data = [
    ["Sanctum", 0, 0],
    ["Outer Sanctum", 1, 4],
    ["Arcwood Pass", 1, 4],
    ["Effold Terrace", 1, 10],
    ["Tuul Valley", 8, 14],
    ["Sanctum Catacombs lvl 1", 1, 6],
    ["Sanctum Catacombs lvl 2", 6, 12],
    ["Sanctum Catacombs lvl 3", 12, 18],
    ["Crescent Road", 8, 14],
    ["Tuul Enclave", 13, 16],
    ["Luvora Garden", 13, 18],
    ["Crescent Keep", 8, 13],
    ["Bularr Fortress", 17, 32],
    ["Crescent Grove lvl 1", 15, 20],
    ["Crescent Grove lvl 2", 20, 25]
]

fishing_grind_data = [
    ["Sanctum", 1, 3],
    ["Arcwood Pass", 3, 6],
    ["Crescent Road", 6, 10]
]

mining_grind_data = [
    ["Arcwood Pass", 1, 2],
    ["Effold Terrace", 1, 2],
    ["Arcwood Pass", 2, 3],
    ["Effold Terrace", 2, 3],
    ["Outer Sanctum", 2, 3],
    ["Crescent Keep", 2, 3],
    ["Tuul Enclave", 2, 3],
    ["Tuul Valley", 3, 6],
    ["Crescent Keep", 3, 6],
    ["Tuul Enclave", 6, 10]
]

enemy_data = {
    "Lesser Wisp": [1, ["Outer Sanctum", "Arcwood Pass", "Sanctum Catacombs lvl 1"]],
    "Slime": [1, ["Outer Sanctum", "Arcwood Pass", "Effold Terrace"]],
    "Tar Spawn": [3, ["Sanctum Catacombs lvl 1", "Effold Terrace"]],
    "Greater Wisp": [4, ["Sanctum Catacombs lvl 1", "Sanctum Catacombs lvl 2", "Effold Terrace", "Arcwood Pass"]],
    "Mini Geist": [4, ["Sanctum Catacombs lvl 1"]],
    "Slimek": [5, ["Effold Terrace"]],
    "Deathgel": [6, ["Sanctum Catacombs lvl 2"]],
    "Geist": [7, ["Sanctum Catacombs lvl 1", "Sanctum Catacombs lvl 2"]],
    "Mekboar": [8, ["Crescent Keep", "Tuul Valley"]],
    "Mini Golem": [8, ["Crescent Keep", "Crescent Road"]],
    "Toxin": [8, ["Sanctum Catacombs lvl 2", "Sanctum Catacombs lvl 3"]],
    "Blightwood": [9, ["Crescent Road", "Crescent Keep"]],
    "Mouth": [10, ["Crescent Road", "Crescent Keep"]],
    "Golem": [12, ["Crescent Road", "Crescent Keep"]],
    "Hellsludge": [13, ["Sanctum Catacombs lvl 3"]],
    "Klamkull": [13, ["Crescent Road", "Luvora Garden"]],
    "Wizboar": [13, ["Tuul Valley", "Tuul Enclave", "Crescent Keep"]],
    "Miasma": [14, ["Sanctum Catacombs lvl 3"]],
    "Vout": [14, ["Tuul Enclave"]],
    "Deadwood": [15, ["Crescent Grove lvl 1"]],
    "Stezza": [16, ["Crescent Grove lvl 1"]],
    "Alshar": [16, ["Crescent Grove lvl 1"]],
    "Blue Minichroom": [16, ["Crescent Grove lvl 1"]],
    "Red Minichroom": [16, ["Crescent Grove lvl 1"]],
    "Rageboar": [17, ["Bularr Fortress"]],
    "Maw": [17, ["Crescent Grove lvl 1"]],
    "Mandragora": [18, ["Luvora Garden"]],
    "Gale Muchroom": [20, ["Crescent Grove lvl 2"]],
    "Aqua Muchroom": [20, ["Crescent Grove lvl 2"]],
    "Firebreath": [24, ["Crescent Grove lvl 2"]],
    "Poltergeist": [16, ["Sanctum Catacombs lvl 3"]],
    "Vultia": [16, ["Tuul Enclave"]],
    "Boomboar": [18, ["Bularr Fortress"]],
    "Carbuncle": [18, ["Crescent Grove lvl 1"]],
    "Monolith": [19, ["Crescent Grove lvl 1"]],
    "Nagrath": [20, ["Crescent Grove lvl 2"]],
    "Barknaught": [22, ["Crescent Grove lvl 2"]],
    "Warboar": [23, ["Bularr Fortress"]],
    "Sirius": [23, ["Crescent Grove lvl 2"]],
    "Death Knight": [24, ["Crescent Grove lvl 2"]],
    "Demigolem": [24, ["Crescent Grove lvl 2"]],
    "Biggun": [4, ["Outer Sanctum"]],
    "Nograd": [4, ["Outer Sanctum"]],
    "Rokkamek": [14, ["Tuul Valley"]],
    "Dolkin": [14, ["Crescent Road"]],
    "Gahool": [15, ["Tuul Enclave"]],
    "Kruole": [21, ["Bularr Fortress"]],
    "Slime Diva": [10, ["Effold Terrace"]],
    "Lord Zuulneruda": [12, ["Sanctum Catacombs lvl 2"]],
    "Lord Kaluuz": [18, ["Sanctum Catacombs lvl 3"]],
    "Colossus": [20, ["Crescent Grove lvl 1"]],
    "Valdur": [25, ["Crescent Grove lvl 2"]],
    "Galius": [26, ["Bularr Fortress"]]
}

portal_counts = {
    "Sanctum": 0,
    "Outer Sanctum": 1,
    "Arcwood Pass": 2,
    "Sanctum Catacombs lvl 1": 3,
    "Sanctum Catacombs lvl 2": 4,
    "Sanctum Catacombs lvl 3": 5,
    "Effold Terrace": 6,
    "Tuul Valley": 7,
    "Crescent Road": 8,
    "Luvora Garden": 9,
    "Crescent Keep": 10,
    "Tuul Enclave": 11,
    "Crescent Grove lvl 1": 12,
    "Crescent Grove lvl 2": 13,
    "Bularr Fortress": 14,
}

from typing import Dict, Set

# Gated equipment: fishing/mining milestones and late level checks accept filler only.
_HIGH_LEVEL_JUNK_MILESTONES = frozenset({"Reach Level 28", "Reach Level 30", "Reach Level 32"})

location_name_groups: Dict[str, Set[str]] = {
    "Quests": {name for name, _region in quests},
    "Levels": {name for name, _region in levels},
    "Shops": {name for name, _region in merchants},
    "Professions": {name for name, _region in professions},
    "Achievements": {name for name, _region in achievements},
    "Bosses": {name for name, _region in bosses},
    "Profession Tool Buys": {name for name, _item in PROFESSION_TOOL_BUYS},
    "Junk Slots": {name for name, _region in professions} | set(_HIGH_LEVEL_JUNK_MILESTONES),
}